// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-06-19 11:59 UTC",
  "date_range": "18 Jun 2026 – 19 Jun 2026",
  "total_scanned": 31,
  "total_categorised": 14,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 4,
      "top": [
        {
          "title": "Midjourney Scanner  🏥,  AWS vs Nvidia ⚡,  agent loop architecture 👨‍💻 ",
          "sender": "TLDR",
          "date": "19 Jun 2026",
          "snippet": "AI startup Midjourney has announced a hardware project in the personal health and medical sector. Its full-body ultrasound machine ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "SpaceX, OpenAI and Anthropic: The S&P 500 Inclusion Question and Investment\r\n Consequences!",
          "sender": "Aswath Damodaran from Musings on Markets",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://aswathdamodaran.substack.com/p/spacex-openai-and-anthropic-the-s Over the last few weeks, attention has (rightly) been focu…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9hc3dhdGhkYW1vZGFyYW4uc3Vic3RhY2suY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmFzd2F0aGRhbW9kYXJhbi5zdWJzdGFjay5jb20lMkZwJTJGc3BhY2V4LW9wZW5haS1hbmQtYW50aHJvcGljLXRoZS1zIiwicCI6MjAyNjQ4ODMxLCJzIjo4MTU2NjcsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODIxNzQzLCJleHAiOjIwOTczOTc3NDMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.IZBgZCywvyow3T_v9z2ESSAXyg-zLdv1mrwWi6Icqo0?",
          "category": "hpc_ai"
        },
        {
          "title": "iPhone Air 2  📱,  inside Anthropic ban ⚖️,  Claude Design + Code 👨‍💻",
          "sender": "TLDR",
          "date": "18 Jun 2026",
          "snippet": "The second-generation iPhone Air is now in advanced testing. Apple plans to launch the device in Spring 2027. The device will retain its current look ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "Midjourney Scanner  🏥,  AWS vs Nvidia ⚡,  agent loop architecture 👨‍💻 ",
          "sender": "TLDR",
          "date": "19 Jun 2026",
          "snippet": "AI startup Midjourney has announced a hardware project in the personal health and medical sector. Its full-body ultrasound machine ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "SpaceX, OpenAI and Anthropic: The S&P 500 Inclusion Question and Investment\r\n Consequences!",
          "sender": "Aswath Damodaran from Musings on Markets",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://aswathdamodaran.substack.com/p/spacex-openai-and-anthropic-the-s Over the last few weeks, attention has (rightly) been focu…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9hc3dhdGhkYW1vZGFyYW4uc3Vic3RhY2suY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmFzd2F0aGRhbW9kYXJhbi5zdWJzdGFjay5jb20lMkZwJTJGc3BhY2V4LW9wZW5haS1hbmQtYW50aHJvcGljLXRoZS1zIiwicCI6MjAyNjQ4ODMxLCJzIjo4MTU2NjcsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODIxNzQzLCJleHAiOjIwOTczOTc3NDMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.IZBgZCywvyow3T_v9z2ESSAXyg-zLdv1mrwWi6Icqo0?",
          "category": "hpc_ai"
        },
        {
          "title": "iPhone Air 2  📱,  inside Anthropic ban ⚖️,  Claude Design + Code 👨‍💻",
          "sender": "TLDR",
          "date": "18 Jun 2026",
          "snippet": "The second-generation iPhone Air is now in advanced testing. Apple plans to launch the device in Spring 2027. The device will retain its current look ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "Databricks Real-Time Lakehouse  🧱, OpenAI’s  Simulated Safety  🚦, Finding Data Pitfalls  🕵️",
          "sender": "TLDR Data",
          "date": "18 Jun 2026",
          "snippet": "Databricks Lakehouse//RT is a real-time data warehouse powered by Reyden that delivers millisecond query performance directly on lakehouse data ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "product",
      "name": "Product Management",
      "emoji": "🗺️",
      "count": 1,
      "top": [
        {
          "title": "The Mom-and-Pop SaaS era has arrived",
          "sender": "Lenny's Newsletter",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/cp/202598945 Unsubscribe https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xld…",
          "link": "https://substack.com/redirect/f018f539-d48c-4d9e-9352-d07cf87bacff?j=eyJ1IjoiN2Nsa25iIn0.O-PU_p3YxNsPpIcNo2SnqduSPxlu3BMzlf29XX0Kpxs",
          "category": "product"
        }
      ],
      "all": [
        {
          "title": "The Mom-and-Pop SaaS era has arrived",
          "sender": "Lenny's Newsletter",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/cp/202598945 Unsubscribe https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xld…",
          "link": "https://substack.com/redirect/f018f539-d48c-4d9e-9352-d07cf87bacff?j=eyJ1IjoiN2Nsa25iIn0.O-PU_p3YxNsPpIcNo2SnqduSPxlu3BMzlf29XX0Kpxs",
          "category": "product"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 8,
      "top": [
        {
          "title": "Efficient agent memory  🗄️,  GitHub malware  🥷,  enterprise MCP  💼",
          "sender": "TLDR Dev",
          "date": "19 Jun 2026",
          "snippet": "A persistent agent memory layer built on Elasticsearch uses a multi-index system to improve long-term memory capabilities for agents ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "S3 Annotations  ☁️,  Rogue Agent 🥷,  PostgreSQL on Kubernetes 📊",
          "sender": "TLDR DevOps",
          "date": "19 Jun 2026",
          "snippet": "Amazon S3 annotations is a new metadata feature that lets users attach up to 1 GB of business context per object across 1,000 named annotations ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "The Mom-and-Pop SaaS era  🛍️, disposable software  🗑️,  chat based onboarding  🧑‍💻💬",
          "sender": "TLDR Product",
          "date": "19 Jun 2026",
          "snippet": "AI reduces the cost of building software, democratizing product creation. As software becomes viable for more niches, \"mom-and-pop SaaS\" ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "Efficient agent memory  🗄️,  GitHub malware  🥷,  enterprise MCP  💼",
          "sender": "TLDR Dev",
          "date": "19 Jun 2026",
          "snippet": "A persistent agent memory layer built on Elasticsearch uses a multi-index system to improve long-term memory capabilities for agents ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "S3 Annotations  ☁️,  Rogue Agent 🥷,  PostgreSQL on Kubernetes 📊",
          "sender": "TLDR DevOps",
          "date": "19 Jun 2026",
          "snippet": "Amazon S3 annotations is a new metadata feature that lets users attach up to 1 GB of business context per object across 1,000 named annotations ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "The Mom-and-Pop SaaS era  🛍️, disposable software  🗑️,  chat based onboarding  🧑‍💻💬",
          "sender": "TLDR Product",
          "date": "19 Jun 2026",
          "snippet": "AI reduces the cost of building software, democratizing product creation. As software becomes viable for more niches, \"mom-and-pop SaaS\" ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "ChatGPT marketshare drops  📉,  Vercel eve 🤖,  Replit links Claude  🔌",
          "sender": "TLDR AI",
          "date": "18 Jun 2026",
          "snippet": "ChatGPT's market share has dipped below 50% for the first time. Users are migrating to other assistants like Google's Gemini ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "OpenBSD Auth Bypass  🐡,  FortiBleed Hits 30K 🛡️,  Peter Thiel Data Leak 📂",
          "sender": "TLDR InfoSec",
          "date": "18 Jun 2026",
          "snippet": "Argus disclosed a PAP authentication bypass in OpenBSD’s sppp(4) subsystem, where sppp_pap_input() in sys/net/if_spppsubr.c fed attacker-controlled ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "S3 Gets Smarter Metadata  🧠,  AI Data Centers Hit Reality Check  🏗️,  Okta Secures AI Agents  🔐",
          "sender": "TLDR IT",
          "date": "18 Jun 2026",
          "snippet": "S3 annotations is a new Amazon S3 metadata capability that lets customers attach up to 1,000 named annotations per object (up to 1 MB each) ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "KFC  Rebrand  🍗,  Foldable iPhone Plans 📱,  Figma Expands MCP  🎨",
          "sender": "TLDR Design",
          "date": "18 Jun 2026",
          "snippet": "KFC has unveiled a major global rebrand developed with JKR, refreshing everything from its logo, typography, packaging, and digital presence ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Agentic coding for all  🏟,  converse more 🗣,  building AI-native startups 🛠",
          "sender": "TLDR Dev",
          "date": "18 Jun 2026",
          "snippet": "A clear division of labor exists in agentic coding where humans make the majority of planning decisions while the AI handles technical execution ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "stoic",
      "name": "Stoicism & Philosophy",
      "emoji": "🧘",
      "count": 1,
      "top": [
        {
          "title": "How to Use Anger as Fuel",
          "sender": "StoicWisdoms",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/how-to-use-anger-as-fuel As a child I could not control my anger at all. When it came it arrived as …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZob3ctdG8tdXNlLWFuZ2VyLWFzLWZ1ZWwiLCJwIjoyMDI1ODM5ODcsInMiOjE4MDEzMzMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODU3MDk0LCJleHAiOjIwOTc0MzMwOTQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.MTD6kebyfkUDtl2OOqkTZBs61OhFoUx_UptAyU57rJE?",
          "category": "stoic"
        }
      ],
      "all": [
        {
          "title": "How to Use Anger as Fuel",
          "sender": "StoicWisdoms",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/how-to-use-anger-as-fuel As a child I could not control my anger at all. When it came it arrived as …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZob3ctdG8tdXNlLWFuZ2VyLWFzLWZ1ZWwiLCJwIjoyMDI1ODM5ODcsInMiOjE4MDEzMzMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODU3MDk0LCJleHAiOjIwOTc0MzMwOTQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.MTD6kebyfkUDtl2OOqkTZBs61OhFoUx_UptAyU57rJE?",
          "category": "stoic"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 17,
      "top": [
        {
          "title": "🩻 Midjourney’s  wild medical hardware pivot",
          "sender": "The Rundown AI",
          "date": "19 Jun 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/step-into-midjourney-s-spa-for-a-body-scan?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_EGgn6tG7M8fMlrcFSTUVNs2HVT7lv9IH-BRf-G8fypJ_EjEV251anjfJ09bPuszn3qGi_4t-GcBjYo1m_rDfeGJnRGG9kA_gqomQqrbMmpcefdECtQu1Db4iGQQVTk6OnomMnF2RLzsTegcGCV2r5IVcUBIPxWtl3wz-NyNaJ-zzQeGtYt9kjXdh5V3DTMBsboFLtSQaUilSD0J7tgBKZW8r-larGG2Ej18PKUic__UxEr0mHe3iszS_GjQX_g3ojgMSEzmOPiJ9rRb5hhHk4rk9GBdE_iv_nZiZsxJdhwkO7FpPWCHzeqHmjXXh46yGwlybtOMXMogeSk_W68w2Q_hoinvTT7b0Mti3_lYGRcFIFsxm98X7_NRfedZH2nmGSXLtV6FVvZXK6ekCKj6xk1RSBG33f305UVF_tmFBQQbdaSdlUp6uTz303wR2rkzlT1KKPOsorB1ynIsFLAsY-ItRYsRjdmHC8FiSvPPNJNZWH_r_6twqKeyCwec-fZ7uWtFZ1HT5iGNZsgELNODzK9aEKozKx6GU6sz3OJV7N8W_wv__p11nELILxm7lC24Ic4XzdvgpFvn5ckccIZwKhVuKWkOZY7bxd6k8Yvi_SQrpblIhZQLT-OFtFtv7qtkOReTGEpvW0ja45xlLZDFM3OrDS7ULO4-JFIMihlqlQUHytVLwzniEX8Pd-IZX-bPRNg8OAMk74twGPobA6PXS2QVK-6V4-1bMbnj4iUwbKEaxFeCRH1qyC44CVfIJbjYJk/4rm/Z313bmSmQPSd5OcIlWhLRA/h0/h001.umo7LWJWwMmOxvFn9eWhRLm-8ENmhqZIls4OqEaIG6g",
          "category": "other"
        },
        {
          "title": "The Secret Architecture Behind AI Data Centers",
          "sender": "Neo Kim",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/what-is-ai-infrastructure Get my system design playbook for FREE on newsletter signup: Share …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRndoYXQtaXMtYWktaW5mcmFzdHJ1Y3R1cmUiLCJwIjoyMDA5MjM3MjIsInMiOjE1MTE4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODYwNDI3LCJleHAiOjIwOTc0MzY0MjcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.78zp6teNoK0umddMpLahLyH6zqXsIjlNejbr42JuHkM?",
          "category": "other"
        },
        {
          "title": "[AINews] GLM > GPT? GLM-5.2 passes vibe check; Z.ai forecasts Open Fable by\r\n December",
          "sender": "AINews",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-glm-gpt-glm-52-passes-vibe Don’t miss out on our Anj Midha episode [ https://substack.com/redirec…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWdsbS1ncHQtZ2xtLTUyLXBhc3Nlcy12aWJlIiwicCI6MjAyNjc4ODM2LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4MTg0ODYzOCwiZXhwIjoyMDk3NDI0NjM4LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.VLbO6TEQ-mCdwzuQWN9Yo71prsGFsQW8L3cAtQ4_h1k?",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "🩻 Midjourney’s  wild medical hardware pivot",
          "sender": "The Rundown AI",
          "date": "19 Jun 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/step-into-midjourney-s-spa-for-a-body-scan?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_EGgn6tG7M8fMlrcFSTUVNs2HVT7lv9IH-BRf-G8fypJ_EjEV251anjfJ09bPuszn3qGi_4t-GcBjYo1m_rDfeGJnRGG9kA_gqomQqrbMmpcefdECtQu1Db4iGQQVTk6OnomMnF2RLzsTegcGCV2r5IVcUBIPxWtl3wz-NyNaJ-zzQeGtYt9kjXdh5V3DTMBsboFLtSQaUilSD0J7tgBKZW8r-larGG2Ej18PKUic__UxEr0mHe3iszS_GjQX_g3ojgMSEzmOPiJ9rRb5hhHk4rk9GBdE_iv_nZiZsxJdhwkO7FpPWCHzeqHmjXXh46yGwlybtOMXMogeSk_W68w2Q_hoinvTT7b0Mti3_lYGRcFIFsxm98X7_NRfedZH2nmGSXLtV6FVvZXK6ekCKj6xk1RSBG33f305UVF_tmFBQQbdaSdlUp6uTz303wR2rkzlT1KKPOsorB1ynIsFLAsY-ItRYsRjdmHC8FiSvPPNJNZWH_r_6twqKeyCwec-fZ7uWtFZ1HT5iGNZsgELNODzK9aEKozKx6GU6sz3OJV7N8W_wv__p11nELILxm7lC24Ic4XzdvgpFvn5ckccIZwKhVuKWkOZY7bxd6k8Yvi_SQrpblIhZQLT-OFtFtv7qtkOReTGEpvW0ja45xlLZDFM3OrDS7ULO4-JFIMihlqlQUHytVLwzniEX8Pd-IZX-bPRNg8OAMk74twGPobA6PXS2QVK-6V4-1bMbnj4iUwbKEaxFeCRH1qyC44CVfIJbjYJk/4rm/Z313bmSmQPSd5OcIlWhLRA/h0/h001.umo7LWJWwMmOxvFn9eWhRLm-8ENmhqZIls4OqEaIG6g",
          "category": "other"
        },
        {
          "title": "The Secret Architecture Behind AI Data Centers",
          "sender": "Neo Kim",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/what-is-ai-infrastructure Get my system design playbook for FREE on newsletter signup: Share …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRndoYXQtaXMtYWktaW5mcmFzdHJ1Y3R1cmUiLCJwIjoyMDA5MjM3MjIsInMiOjE1MTE4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODYwNDI3LCJleHAiOjIwOTc0MzY0MjcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.78zp6teNoK0umddMpLahLyH6zqXsIjlNejbr42JuHkM?",
          "category": "other"
        },
        {
          "title": "[AINews] GLM > GPT? GLM-5.2 passes vibe check; Z.ai forecasts Open Fable by\r\n December",
          "sender": "AINews",
          "date": "19 Jun 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-glm-gpt-glm-52-passes-vibe Don’t miss out on our Anj Midha episode [ https://substack.com/redirec…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWdsbS1ncHQtZ2xtLTUyLXBhc3Nlcy12aWJlIiwicCI6MjAyNjc4ODM2LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4MTg0ODYzOCwiZXhwIjoyMDk3NDI0NjM4LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.VLbO6TEQ-mCdwzuQWN9Yo71prsGFsQW8L3cAtQ4_h1k?",
          "category": "other"
        },
        {
          "title": "Your Shopify theme could get your Google account suspended",
          "sender": "Nord Media",
          "date": "18 Jun 2026",
          "snippet": "********************************************************** Your Shopify theme could get your Google account suspended ******************************************…",
          "link": "https://735d96f7.click.convertkit-mail4.com/d0umrl8w7mf0ho92383imhz95edv9s2qxep4vmz4mvw5dr6xp6wo0rwqn3e43rwqzl92lx9rxkz7w0zr5x3k85nql079w0qn6393wrxw4n9xoxmx07530nwrx4nf547mm/48hvh7umd5vp68fqu7/aHR0cHM6Ly9wb3N0c2NyaXB0LmlvL3Ntcy1tYXJrZXRpbmctY2FsZW5kYXItc2lnbnVwP3V0bV9zb3VyY2U9a29keV9ub3JkcXVpc3QmdXRtX21lZGl1bT1zcG9uc29yc2hpcCZ1dG1fY2FtcGFpZ249MjAyNl9zbXNfY2FsZW5kYXImdXRtX2NvbnRlbnQ9MThfanVuXzIwMjY=",
          "category": "other"
        },
        {
          "title": "Open Tab: Hunter Harris",
          "sender": "Substack",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://on.substack.com/p/open-tab-hunter-harris Hunter Harris is the creator of Hung Up , the twice-weekly Substack newsletter whe…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9vbi5zdWJzdGFjay5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGb24uc3Vic3RhY2suY29tJTJGcCUyRm9wZW4tdGFiLWh1bnRlci1oYXJyaXMiLCJwIjoyMDI1MDU1NjgsInMiOjEsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxODA1NjkwLCJleHAiOjIwOTczODE2OTAsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.cVOBrQahfyebYWpgljES5gE6yBF-1V0GUq7vyL5-Qzo?",
          "category": "other"
        },
        {
          "title": "The Professor of Outputmaxxing — Anjney Midha, AMP",
          "sender": "Latent.Space",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/anj Last 4 days before regular tickets sell out at AI Engineer World’s Fair [ https://substack.com/redir…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYW5qIiwicCI6MjAyMzU5Nzk3LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4MTgwMzk2NCwiZXhwIjoyMDk3Mzc5OTY0LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.SkdnpSGQ4F0lroSeDhULmQuoajx0z18IF3_EmQ97dCg?",
          "category": "other"
        },
        {
          "title": "Dario Amodei's full picture: 10 takeaways that matter",
          "sender": "The AI Corner",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.the-ai-corner.com/p/dario-amodei-circuit-documentary-10-takeaways-2026 Anthropic is worth nearly a trillion dollars. It…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhlLWFpLWNvcm5lci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnRoZS1haS1jb3JuZXIuY29tJTJGcCUyRmRhcmlvLWFtb2RlaS1jaXJjdWl0LWRvY3VtZW50YXJ5LTEwLXRha2Vhd2F5cy0yMDI2IiwicCI6MjAxODAyMDY5LCJzIjo2ODUwNTQ0LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4MTgwMzc1MCwiZXhwIjoyMDk3Mzc5NzUwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.FThjSwhtvWAXWnyHmZoWLYrx8dbsf_EUVY0juV9ew3g?",
          "category": "other"
        },
        {
          "title": "This is How You Get Your Homepage Viral",
          "sender": "The VC Corner",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/reddit-playbook-startup-founders The Reddit Playbook Every Startup Founder Is Ignoring 2 years ago to…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGcmVkZGl0LXBsYXlib29rLXN0YXJ0dXAtZm91bmRlcnMiLCJwIjoxOTI5MjY2MDgsInMiOjIxMjUxODMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxNzk5NTY4LCJleHAiOjIwOTczNzU1NjgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.5E42jyL-ihcGGe3n916TGoq40W2ymouQWn7OR3rLcUI?",
          "category": "other"
        },
        {
          "title": "Observability for Beginners: Logs, Metrics, Traces, and Everything Around Them",
          "sender": "ByteByteGo",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/observability-for-beginners-logs Observability for Beginners: Logs, Metrics, Traces, and Everything A…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGb2JzZXJ2YWJpbGl0eS1mb3ItYmVnaW5uZXJzLWxvZ3MiLCJwIjoyMDI1MjY5MTEsInMiOjgxNzEzMiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODE3OTc2MTQsImV4cCI6MjA5NzM3MzYxNCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.ypsnrJjbvn7fweyWzR7ttyCNBryYdAOyZ7-n7QbaazE?",
          "category": "other"
        },
        {
          "title": "🤖  Meet Eno, the anti-humanoid robot",
          "sender": "The Rundown Robotics",
          "date": "18 Jun 2026",
          "snippet": "^**[Read Online](https://robotnews.therundown.ai/p/meet-eno-the-anti-humanoid-robot?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJzY3JpYmVyX2lkIjoiZTMxY…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.GQOM8q4ys-vZgCzT2HGlhRR7J-xBT4QBkF5vOL2NbkARBNH8cfj-RV4IBWDhnTqzHg23bmmxFtxJeayQh5kENn1dKi4m6lijnarO6zOkZWnyIgWDmD4R3ymbzWE8e6JN-hPVIiSwLEfvR0Dsp-JHktioAMQvxNzRVE-22u37sQY7zgJ-9wQhCHIkQ7gdVM8Qapeyne7bTMSHn5aKz4CqI_wFj0ZEYNKQvjtw7IbGCJnpLIxow7BrxHwkmZJkWTGSW9Bu9LwqyWPM4GklNfl41xsBf7K8DLsBsasqN6Gh8ATWD9tjogUK8xY0PZ_i0fYJOufzGyl9GqOm0prAR2ry0AkR8abFRIL7II0_SaAXd_D8xk2Xpe9dK86HZ-W_vruega6Ro7WEpgceB8JXoi8l3f4FVGXZwbPgW3X7QQxZN-kQEbvG30ahqZaqPjIfsPKpKE1xB2lbwn18PF3JAoTIOER6N35LcpQeEl-uM_iA-Nb5K0kjZSUwbLl4QXWSK4y4L3xFzIPXY_xOA8FSBFzA-OzI-zZOdjMHdNvcclvx-SSeuEx24OnK1NxXWksY8D-XFBvUdKtF7G9IQ7m7SkRr0aoaWhixVVjo-m3dftQnNwQ_a0aRaZtxNZ4mRfPvJ8oFSDsexN0VGzOmguTrKf260tX5MjAOXW-HCCw1D494PrJ5-igKtHQD0k01K_1tRC8Z5lL-vXWStxpOMukKJm1DmA/4rl/3w3-njLqTBi6hcJ37gII5g/h0/h001.C6gM0P2-EtZy0XVl27sqQt-aZLZl5Hmr95Gt7XL6Iu8",
          "category": "other"
        },
        {
          "title": "🚀  Vercel open sources Eve",
          "sender": "The Code",
          "date": "18 Jun 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/ce6df015-4959-4022-b78c-9449ded76…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.kro7WBsAmEsY5mGgiUDePbOdMF_BvViPt7FxYKgxL9sdSnuI5PhTfFcfyHDxXTcXfPCnfQ_RrAiQaexQTOV6QDQVjOCsOBnLMu47yNkd216Nz0riZrJ5_CkU7acMm9oKro1-3PGVWX8KNDDwO_LSvQAgOiHdAhmZA2hkREpJvpexeqK00LYXwcXWqPhj4hll3P8Ap55vHAUtKwQfo18JKF8rM_KfTLS7kT8-5r_kDB_EZfLbnM5At1xNXeW6Dg2wO97LPuafSe4yidqMyIetJJs1j3auPHptjU5Fi93-4ypBVCrpGdLCRThOvd8mL7pBmLPNJEelmaP28MzwQ41Ol1NI822AjjexizAf6GxQnJ8C58wAFpRiQzz-aMq_jnTZBKyq4bYYt_9TKMxQmk6WZbArBIBfE3G8lwDJe3fYACW8vt5KZs0iUpKh44EI4aaMxuAb3xK8J56JDtHp8RUnqe7acztdjdkgtPRJ2ohfmKIx8ATH1gsCd1SQsxmG1njNBk9l0P8cNRr3ScXNhB9-lFBQuvkxeeQgpUA2UQTSgr9_gzmXgbcP7OjfQDZR7POuqNuFqZX3OaWGAYLFgnVRhwdWrR7gb36mSZa2sKo2lfEvP2a6n0A7999XJaiQ8xG0Cg_vuOdBrRthc9uVu1OiGSOVMPc7YFOA_Y15bwH8c157Q6XgBIyteQ0CXpr5p40_UIdpLcha-swLaK069OTgRrAvi4s-cJCOpoAb2Ab2ZWuk4XBh_OqQ_LoQFNpaAED1cuPij6T4wuY8S2T18xFVh-V7FgvqzzovkUNj2Kq9PU0qIZ2i4V0yZICsaOJU_h6mbiUu0kkG9ODBMghjbucYKg/4rl/43bscjxMQ7-QWrdjkR9zKA/h0/h001.54vcsxeuorcI3aBpPWSZNGnP9lF2FiGQ7HVLSkpIAVo",
          "category": "other"
        },
        {
          "title": "How to Do Performance Reviews",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/how-to-do-performance-reviews Intro Performance reviews play an important part in any organ…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZob3ctdG8tZG8tcGVyZm9ybWFuY2UtcmV2aWV3cyIsInAiOjE2MTM3NzU1NywicyI6MTExNTgxNSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODE3ODg3ODUsImV4cCI6MjA5NzM2NDc4NSwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.5ZBmkP00T7AfT-_o7_xupEg-s9fYnMoIkTHCtSryWf4?",
          "category": "other"
        },
        {
          "title": "📉  Meta's worst morale in years",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "18 Jun 2026",
          "snippet": "---------- View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/1a502a84-2232-407d-95c…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGUxJQ1tuM0VI9bZ93JY-zbwTRPb_bEqKkAEikfQ1EDzj_vI15RwOfN1rhs_4sROWmLwCCVYxo5Xc-ua8SxrAtqXITpMPVw4uD9417VpgVMel1h3_JrTjRS7M4T9lAh8-1kVva0iIXWeWzMNbwcUraZz9aD35McLwSZQIDwEFc3EVKgzuyAHbbX_V-S0nDqFfUeAqzDVx3MN3rooBF1vmaGbtqyBgiCMS5dRm1Pslzhf08Yvmc0btFWG4qPAc_Cp-96BXzdJ0OOwRb03j9G1ONjSC25zEk5NaWv5VAIXmjWbqRQBoMLZqrzNmUPU65EnfvOKZjT5_1tgj7ANdoHAu7ZwvVeGMTAFvIu7adQs53D4rw5nF2DAFYh6pvgGSK-WZ9yd632PoNOPosObIaQbldq8K8KTaG8kmtK8kWdtAxzKeUG12fJyAjicH7sRHmHC7B0LhjLyXFkurgvuU5sQ2JZireuRkGv4tibf-vvD26BhYADymL_r4Q8N-DDwZi-ukOBiOIQ1l1-qmHTKGxcSoAJeJAeuAfnBaAoZqSIiiCl21hFrmXLMsd58QVROVcHsdF9vGf3apoITXh6WwJs0_Wp42Rb2H90WwXM5frUY2LGpRPwXGaYxEpp4jrmg-wjpt2Egy85gNgbAtFPUhyitgU9_6-rzP-LibYhivHX-8S1svxIqNXj1uNCcXWRIQ9s1RgPLpgAN4bHNlNqATQPgE9hK/4rl/El9cdoZPR5yAr3JkZO0eAw/h0/h001.4lVBhSjZ37u34XVLqNamZd_PKRpQmFsmkUSPdWObkjE",
          "category": "other"
        },
        {
          "title": "The Mom-and-Pop SaaS era has arrived",
          "sender": "Elena's Growth Scoop",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.elenaverna.com/p/the-mom-and-pop-saas-era-has-arrived So many stories about AI focus on developer productivity or repla…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuZWxlbmF2ZXJuYS5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LmVsZW5hdmVybmEuY29tJTJGcCUyRnRoZS1tb20tYW5kLXBvcC1zYWFzLWVyYS1oYXMtYXJyaXZlZCIsInAiOjIwMjU0NTU4OSwicyI6MTQzNTI0OSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODE3ODAwMTAsImV4cCI6MjA5NzM1NjAxMCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.scgGi2p7k6Qk2mpC-QscmFaFhb2_-588xcKCNJP_Ilg?",
          "category": "other"
        },
        {
          "title": "🔒  Inside the deadlock keeping Mythos offline",
          "sender": "The Rundown AI",
          "date": "18 Jun 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/inside-the-deadlock-keeping-mythos-offline?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_Eu2S_mKhKF5NDedDj5MBqO5y2S7Go9cQOVv-teFqycdp1WHU1DAmh_3lLWp2AIzpVdORk6i1SNZTX3ZavwJGZKdlnbtFdXQwzhSLmUEZrjHeIldp96u99fJUWUZRbpJWbXDPNkeiBrCTcFeKE2vyjqOZitdV-6_ulob3yOj1jMxJ60Pv5-dUSp85hCiOqpd__HKWWhZfn-rxfuM4HD7IzvSFmZIRlCaIaVpH53IMe14kT6OPldxB-ZZUdXsIqWru2WvA-hDsRFBLJDSY8wCxxKNWkZGxWvCxGOJFoie4OeM__g5MdOU6IEnlN9CXbP8U5u2mvqnjlC0D2wweCrTxFRGQACWo9di3IxrlQ9a2hil2PSVXAQ9aohglEENZlr_q_WhYX2tqBOdcC2UmX3tps4owuc3abhx1tuYhApY1btGkoqVa9I5_SBEVzoQEF-DRI7UyNXXB2W0CQ309QKZ8Q_Riqgeqe_BVOtlNdQ2XEVI0FwG68wSaab-VFUe7KrcbnPnQoywwikKJOQVi-VoXHHaMg7-l9zb6WPp3vwJypye_EUGHdSfaPRZ8Sd8Z_fafvQsvqxGDO5AxGemLUnXlx0-90pN3BsdZXoUfGAZVOQ_Xt6IwWC8VuGT-ZTeMyD8xYt70j9WW2aWuNComw_OW-enB2nzy1IxLkLgCraAYUOArZLlPvqJQoaOnK3v46teD1K0ASHvtF7jjrnyUp9P7Xb_6W-bZ_e_y_hScx0jX9Jmh-9YFfrJ1--fxuoindT8S4/4rl/Ufo2hj9rSD6XJlzHPTO_LA/h0/h001.vBaAhExuHQLhX8bDdjnOH9TEN8cTFOxutkGCAbygw30",
          "category": "other"
        },
        {
          "title": "How to get attention *without* an audience 🪩",
          "sender": "Tom's Marketing Ideas",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/how-to-blow-up-without-an-audience “Tom, your ideas are great, but I only have 400 followers. Is t…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGaG93LXRvLWJsb3ctdXAtd2l0aG91dC1hbi1hdWRpZW5jZSIsInAiOjE5Nzk4NzQ1OSwicyI6MTgxNTQ3MiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODE3NzMwODMsImV4cCI6MjA5NzM0OTA4MywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.KmfNK65SCYVZpfpi1jsb2E24XotKhWOfKxqiilF2ZEk?",
          "category": "other"
        },
        {
          "title": "[AINews] Midjourney Medical: scan your organs like you step on a scale",
          "sender": "AINews",
          "date": "18 Jun 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-midjourney-medical-scan-your It’s a tough choice whether or not the buzzy Midjourney Medical laun…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLW1pZGpvdXJuZXktbWVkaWNhbC1zY2FuLXlvdXIiLCJwIjoyMDI1Mjk0OTAsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzgxNzU2NzA3LCJleHAiOjIwOTczMzI3MDcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.gngcM5G4B7oXE9Oto3uNsoG60eq08S_HhByvUkV2fFE?",
          "category": "other"
        }
      ]
    }
  ]
};
