// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-05-28 11:30 UTC",
  "date_range": "27 May 2026 – 28 May 2026",
  "total_scanned": 32,
  "total_categorised": 12,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 3,
      "top": [
        {
          "title": "HPC AI // Sync Issue # 4",
          "sender": "HPCwire Sync",
          "date": "27 May 2026",
          "snippet": "#outlook a { padding: 0; } .body{ font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Geneva, Verdana, sans-serif; width: 100% !important; -webk…",
          "link": "https://tabor.omeclk.com/portal/wts/uc%5EcnCmdogaqmT2dmEwarcnz2q0rlnEwnTCrx9bEeHRAyS83f4d",
          "category": "hpc_ai"
        },
        {
          "title": "OpenAI Image Watermarks  🔍,  Figma Bulk Grids  📐,  Jony Ive Ferrari 🏎️",
          "sender": "TLDR Design",
          "date": "27 May 2026",
          "snippet": "OpenAI announced two new measures to help identify AI-generated images: adopting the C2PA standard that adds metadata signals ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "Last Week in AI #341 - Musk loses to OpenAI, Google's IO updates, OpenAI solves Erdős",
          "sender": "Last Week in AI",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://lastweekin.ai/p/last-week-in-ai-341-musk-loses-to Top News Elon Musk Loses $150 Billion Suit Against OpenAI and Sam Altman …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9sYXN0d2Vla2luLmFpL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmxhc3R3ZWVraW4uYWklMkZwJTJGbGFzdC13ZWVrLWluLWFpLTM0MS1tdXNrLWxvc2VzLXRvIiwicCI6MTk5NDI4ODA5LCJzIjoxMTAzNTgsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5ODY4MzU4LCJleHAiOjIwOTU0NDQzNTgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.pnEgCWBvFOe7jkZPCf5IpgfNMwC2DfxfREQUvMM1mQU?",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "HPC AI // Sync Issue # 4",
          "sender": "HPCwire Sync",
          "date": "27 May 2026",
          "snippet": "#outlook a { padding: 0; } .body{ font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Geneva, Verdana, sans-serif; width: 100% !important; -webk…",
          "link": "https://tabor.omeclk.com/portal/wts/uc%5EcnCmdogaqmT2dmEwarcnz2q0rlnEwnTCrx9bEeHRAyS83f4d",
          "category": "hpc_ai"
        },
        {
          "title": "OpenAI Image Watermarks  🔍,  Figma Bulk Grids  📐,  Jony Ive Ferrari 🏎️",
          "sender": "TLDR Design",
          "date": "27 May 2026",
          "snippet": "OpenAI announced two new measures to help identify AI-generated images: adopting the C2PA standard that adds metadata signals ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "Last Week in AI #341 - Musk loses to OpenAI, Google's IO updates, OpenAI solves Erdős",
          "sender": "Last Week in AI",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://lastweekin.ai/p/last-week-in-ai-341-musk-loses-to Top News Elon Musk Loses $150 Billion Suit Against OpenAI and Sam Altman …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9sYXN0d2Vla2luLmFpL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmxhc3R3ZWVraW4uYWklMkZwJTJGbGFzdC13ZWVrLWluLWFpLTM0MS1tdXNrLWxvc2VzLXRvIiwicCI6MTk5NDI4ODA5LCJzIjoxMTAzNTgsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5ODY4MzU4LCJleHAiOjIwOTU0NDQzNTgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.pnEgCWBvFOe7jkZPCf5IpgfNMwC2DfxfREQUvMM1mQU?",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 9,
      "top": [
        {
          "title": "How Linear is fast  ⚡️,  curl project pressure  😓,  tech CEO AI psychosis 🧠",
          "sender": "TLDR Dev",
          "date": "28 May 2026",
          "snippet": "Linear, the issue tracking app, has fast performance thanks to a local-first architecture where the database lives in the browser ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Tesla's robot factory  🤖,  space datacenters 🛰️,  future of push notifications 📱",
          "sender": "TLDR",
          "date": "28 May 2026",
          "snippet": "Tesla's new Optimus factory is officially under construction at Gigafactory Texas. The project will add more than 5.2 million square feet ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Slashing Snowflake Costs  ❄️, Open-Source Agent Tradeoffs  🤖, Kafka’s  New Bottleneck  ⚙️",
          "sender": "TLDR Data",
          "date": "28 May 2026",
          "snippet": "Snowflake cost and performance hinge on three separable layers: storage, compute, and cloud services, with the biggest savings coming from ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "How Linear is fast  ⚡️,  curl project pressure  😓,  tech CEO AI psychosis 🧠",
          "sender": "TLDR Dev",
          "date": "28 May 2026",
          "snippet": "Linear, the issue tracking app, has fast performance thanks to a local-first architecture where the database lives in the browser ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Tesla's robot factory  🤖,  space datacenters 🛰️,  future of push notifications 📱",
          "sender": "TLDR",
          "date": "28 May 2026",
          "snippet": "Tesla's new Optimus factory is officially under construction at Gigafactory Texas. The project will add more than 5.2 million square feet ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Slashing Snowflake Costs  ❄️, Open-Source Agent Tradeoffs  🤖, Kafka’s  New Bottleneck  ⚙️",
          "sender": "TLDR Data",
          "date": "28 May 2026",
          "snippet": "Snowflake cost and performance hinge on three separable layers: storage, compute, and cloud services, with the biggest savings coming from ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "xAI Cursor limits  🚫,  DeepSWE 👨‍💻,  China AI travel restrictions  🤖",
          "sender": "TLDR AI",
          "date": "27 May 2026",
          "snippet": "xAI's top lawyer has warned xAI employees to carefully moderate their interactions with workers from Cursor. Staff should not extend beyond ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "600K Lithuanian Records Leaked 🇱🇹,  KnowledgeDeliver 0-Day RCE 💥,  Google Family Link Hijack 📱",
          "sender": "TLDR InfoSec",
          "date": "27 May 2026",
          "snippet": "Lithuanian authorities have disclosed that they suffered a data leak of over 600k entries from national data registers. ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Dropbox Hands Off the AI Pivot  📦,  Agent Runtimes Get Real  🛠️,  Claude Plugs Into Enterprise Security  🔐",
          "sender": "TLDR IT",
          "date": "27 May 2026",
          "snippet": "Dropbox founder Drew Houston is stepping down as CEO, with core-business GM Ashraf Alkarmi becoming co-CEO and eventual successor ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI causes burnout  😮‍💨, modern pixel fonts  🔠,  local AI with outsourcing 🤔",
          "sender": "TLDR Dev",
          "date": "27 May 2026",
          "snippet": "AI-assisted development can lead to cognitive burnout by replacing creative problem-solving with the mental exhaustion of constant code review ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Dropbox’s  Nova  ✨, Migrating to GitHub Enterprise  🧱,  Terraform AgentCore  🪐",
          "sender": "TLDR DevOps",
          "date": "27 May 2026",
          "snippet": "Nova is an internal cloud platform within Dropbox for running coding agents across its engineering workflows. It lets engineers run multiple ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "SpaceX governance  💼,  Nasa picks Blue Origin  🚀,  Chrome's built-in AI 🤖",
          "sender": "TLDR",
          "date": "27 May 2026",
          "snippet": "In January, SpaceX granted Elon Musk a pay package that will eventually total 1.3 billion in restricted shares. While he has not achieved the goals ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 20,
      "top": [
        {
          "title": "🧬  Zuckerberg's lab just had a big AI biology moment",
          "sender": "The Rundown AI",
          "date": "28 May 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/a-world-model-for-proteins-is-here?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiLCJhbG…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_GzwCtV3CI_NFO4br3s5BeuaeqUh3g7il--brw8b8B_XfbY4W97uulhL2RZXp7UcO_AnI5nwayoW1HuTYyng0SFXd7w6sJHMi8v8kBBK5q2DcJVhTrXNKgqNfXmqDTwp27JBVY4mBd_lWK3xlrGiRBUE8uPxVZR80CBDA_C8-CsmjTW1BTsdJsx7BAr_11HGcCkeY33ijvBtYgjpLO0Vhk7huLfiIpCUh8PnLu11diy-9YO1V4th2C5w4qIhS6zOTDOJsNlfKv0zjmez0015AWQYPTpPNGkSRZJj8s1O_CSUUg8JJ1lXke9tOgQi7_XduDsHr5m7O2Wg_GI1Jw3c2Q-5h61YGA-i9MxHxVU5_4n4qcISvwMbDY1ixYM6kXJYu44BH9WqgVbs-k-Elewky0eX2q3DCmTCPVMcBtEghOZ8PDz7SXd7LJkna9Mlo9fzXtvJ1K7dJBWsFELqSeOsKxeTW2oO6a_8wGpB4HSGcn0qdtd6-uHR9BOfTPlVGz6_qkerLWQMr3eqtDDR8y0SDGdt9tsPGpFe7VqpYgVXHYzEYgLhwuEN-F2boBotesqXfEu36pjNuBJPWbVL-lnPDM1uTi82MyD4kLIwFTckseXqquop02mABRwCqko3B4TvGtCXVjGqYX2tzsQmN73GlgjgqD0kOyDheSCoRWdezt2DQtbyfjPWmgAqp5s1kyf4Anug4u4PICjh-mJQvulJ1e6lBjXmxBaoEYL4ct4Nrznyw/4r0/TEKDSMiISwCo26vSbrSt9g/h0/h001.h3lGnV0td9wUuD_-aYWkLiQYxWxHte_le5FZGDygLjg",
          "category": "other"
        },
        {
          "title": "How to get ahead of 99% of software engineers with AI agents",
          "sender": "Neo Kim",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/agentic-ai-use-cases Get my system design playbook for FREE on newsletter signup: Share this …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRmFnZW50aWMtYWktdXNlLWNhc2VzIiwicCI6MTk5MTg1MzY0LCJzIjoxNTExODQ1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3OTk2MjYyMCwiZXhwIjoyMDk1NTM4NjIwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.HFOfOwJfnxnoAJKanUrNdAi7Ttu6ahAb62B3RyEQetg?",
          "category": "other"
        },
        {
          "title": "What to do if your marketing budget is $0 🪫",
          "sender": "Tom's Marketing Ideas",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/what-to-do-if-your-marketing-budget ✨ Today’s free article is sponsored by Warmy ✨ I talk to a lot…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGd2hhdC10by1kby1pZi15b3VyLW1hcmtldGluZy1idWRnZXQiLCJwIjoxOTczODAzOTIsInMiOjE4MTU0NzIsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5OTU4NTM4LCJleHAiOjIwOTU1MzQ1MzgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.h89WewzKPwQyn6ps3t27dbnsCJCjtQgeUYxOVG8K9ds?",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "🧬  Zuckerberg's lab just had a big AI biology moment",
          "sender": "The Rundown AI",
          "date": "28 May 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/a-world-model-for-proteins-is-here?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiLCJhbG…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_GzwCtV3CI_NFO4br3s5BeuaeqUh3g7il--brw8b8B_XfbY4W97uulhL2RZXp7UcO_AnI5nwayoW1HuTYyng0SFXd7w6sJHMi8v8kBBK5q2DcJVhTrXNKgqNfXmqDTwp27JBVY4mBd_lWK3xlrGiRBUE8uPxVZR80CBDA_C8-CsmjTW1BTsdJsx7BAr_11HGcCkeY33ijvBtYgjpLO0Vhk7huLfiIpCUh8PnLu11diy-9YO1V4th2C5w4qIhS6zOTDOJsNlfKv0zjmez0015AWQYPTpPNGkSRZJj8s1O_CSUUg8JJ1lXke9tOgQi7_XduDsHr5m7O2Wg_GI1Jw3c2Q-5h61YGA-i9MxHxVU5_4n4qcISvwMbDY1ixYM6kXJYu44BH9WqgVbs-k-Elewky0eX2q3DCmTCPVMcBtEghOZ8PDz7SXd7LJkna9Mlo9fzXtvJ1K7dJBWsFELqSeOsKxeTW2oO6a_8wGpB4HSGcn0qdtd6-uHR9BOfTPlVGz6_qkerLWQMr3eqtDDR8y0SDGdt9tsPGpFe7VqpYgVXHYzEYgLhwuEN-F2boBotesqXfEu36pjNuBJPWbVL-lnPDM1uTi82MyD4kLIwFTckseXqquop02mABRwCqko3B4TvGtCXVjGqYX2tzsQmN73GlgjgqD0kOyDheSCoRWdezt2DQtbyfjPWmgAqp5s1kyf4Anug4u4PICjh-mJQvulJ1e6lBjXmxBaoEYL4ct4Nrznyw/4r0/TEKDSMiISwCo26vSbrSt9g/h0/h001.h3lGnV0td9wUuD_-aYWkLiQYxWxHte_le5FZGDygLjg",
          "category": "other"
        },
        {
          "title": "How to get ahead of 99% of software engineers with AI agents",
          "sender": "Neo Kim",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/agentic-ai-use-cases Get my system design playbook for FREE on newsletter signup: Share this …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRmFnZW50aWMtYWktdXNlLWNhc2VzIiwicCI6MTk5MTg1MzY0LCJzIjoxNTExODQ1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3OTk2MjYyMCwiZXhwIjoyMDk1NTM4NjIwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.HFOfOwJfnxnoAJKanUrNdAi7Ttu6ahAb62B3RyEQetg?",
          "category": "other"
        },
        {
          "title": "What to do if your marketing budget is $0 🪫",
          "sender": "Tom's Marketing Ideas",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/what-to-do-if-your-marketing-budget ✨ Today’s free article is sponsored by Warmy ✨ I talk to a lot…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGd2hhdC10by1kby1pZi15b3VyLW1hcmtldGluZy1idWRnZXQiLCJwIjoxOTczODAzOTIsInMiOjE4MTU0NzIsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5OTU4NTM4LCJleHAiOjIwOTU1MzQ1MzgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.h89WewzKPwQyn6ps3t27dbnsCJCjtQgeUYxOVG8K9ds?",
          "category": "other"
        },
        {
          "title": "AI-Native Engineering Leadership",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/ai-native-engineering-leadership Intro Yesterday, together with my friends from Augment Cod…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZhaS1uYXRpdmUtZW5naW5lZXJpbmctbGVhZGVyc2hpcCIsInAiOjE5OTEzNjE1MiwicyI6MTExNTgxNSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk5NTQzNTMsImV4cCI6MjA5NTUzMDM1MywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.y-2uohxMBQS9W9ptdKV9AnjKmYHKYKsg08PZ-7V2q-s?",
          "category": "other"
        },
        {
          "title": "[AINews] Cognition raises $1B in $26B Series D",
          "sender": "AINews",
          "date": "28 May 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-cognition-raises-1b-in-26b We last wrote about [ https://substack.com/redirect/517cf117-2bca-48b5…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWNvZ25pdGlvbi1yYWlzZXMtMWItaW4tMjZiIiwicCI6MTk5NTY1NTMxLCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3OTk1MzMyMCwiZXhwIjoyMDk1NTI5MzIwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.lz0Epx7-t-uB7HFbOedtFcBApMPiH8lud9xQAJDzlsA?",
          "category": "other"
        },
        {
          "title": "\"The Quiet Anti-Patterns of AI Inside Organizations\" and 4 more",
          "sender": "Substack",
          "date": "27 May 2026",
          "snippet": "\"The Quiet Anti-Patterns of AI Inside Organizations\" and 4 more @media (max-width: 1024px) { .typography .pullquote-align-left, .typography.editor .pullquote-al…",
          "link": "https://productandleadership.substack.com",
          "category": "other"
        },
        {
          "title": "Sam Altman watched 900 million people talk to one personality every week",
          "sender": "The AI Corner",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://www.the-ai-corner.com/p/sam-altman-chatgpt-personality-900-million-users-10-things-2026 The biggest AI risk [ https://subst…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhlLWFpLWNvcm5lci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnRoZS1haS1jb3JuZXIuY29tJTJGcCUyRnNhbS1hbHRtYW4tY2hhdGdwdC1wZXJzb25hbGl0eS05MDAtbWlsbGlvbi11c2Vycy0xMC10aGluZ3MtMjAyNiIsInAiOjE5NjU5NDI5NywicyI6Njg1MDU0NCwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk5MDY0MDQsImV4cCI6MjA5NTQ4MjQwNCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.b4xeHj6Tak1tkVdgOmWWLhQllsMGKOKmLuzklQ2X_rE?",
          "category": "other"
        },
        {
          "title": "🔬ESMFold2: The Bitter Lesson is Coming for Proteins - Alex Rives, BioHub",
          "sender": "Latent.Space",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/esmfold2 Editor’s note: In our first BioHub pod with Priscilla and Mark [ https://substack.com/redirect/…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGZXNtZm9sZDIiLCJwIjoxOTk0ODc4MzYsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5OTA0MDg0LCJleHAiOjIwOTU0ODAwODQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.pabjn5EXUVwwkmG2RJHcY7PT29ys_sul8Yt1Pilkoes?",
          "category": "other"
        },
        {
          "title": "Replit Was Rejected by YC 3 Times. Then Paul Graham Called Sam Altman\r\n Personally",
          "sender": "The VC Corner",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/replit-pitch-deck-seed-2016-story-playbook-2026 In 2011, Amjad Masad was a developer at Yahoo trying …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGcmVwbGl0LXBpdGNoLWRlY2stc2VlZC0yMDE2LXN0b3J5LXBsYXlib29rLTIwMjYiLCJwIjoxOTk0NzUxODgsInMiOjIxMjUxODMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc5OTAyOTE0LCJleHAiOjIwOTU0Nzg5MTQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.I25kqsM9Y8GuZ0GbHm5A2-7_4UWQwjzSTJ3OHuNyArw?",
          "category": "other"
        },
        {
          "title": "My Internet: Kate Lindsay",
          "sender": "Substack",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://on.substack.com/p/my-internet-kate-lindsay Twice a month, internet-culture publication Embedded logs on with someone extrem…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9vbi5zdWJzdGFjay5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGb24uc3Vic3RhY2suY29tJTJGcCUyRm15LWludGVybmV0LWthdGUtbGluZHNheSIsInAiOjE5OTQxMTg4MiwicyI6MSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk5MDEzNjcsImV4cCI6MjA5NTQ3NzM2NywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.jQhkEMPUn-feaHWXjCdWuraDReAGw-BwSZsRvrsEVbU?",
          "category": "other"
        },
        {
          "title": "Live video with Prof G Media now: Raging Perspective — LIVE with Jessica Tarlov & Aaron Parnas",
          "sender": "Substack",
          "date": "27 May 2026",
          "snippet": "Email from Substack @media (max-width: 1024px) { .typography .pullquote-align-left, .typography.editor .pullquote-align-left, .typography .pullquote-align-right…",
          "link": "https://open.substack.com/live-stream/213181?utm_source=email&amp;utm_campaign=new-live-stream-email",
          "category": "other"
        },
        {
          "title": "How Airtable Built the Search Layer Behind Their AI Features",
          "sender": "ByteByteGo",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/how-airtable-built-the-search-layer WorkOS launches auth.md - an open protocol for agent registration…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGaG93LWFpcnRhYmxlLWJ1aWx0LXRoZS1zZWFyY2gtbGF5ZXIiLCJwIjoxOTg2NzU4MTgsInMiOjgxNzEzMiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk4OTY3ODIsImV4cCI6MjA5NTQ3Mjc4MiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.2dSmbD0N8s9dtQhmUuOCMGiw6Jl0GNAmcRWRUNiWlIc?",
          "category": "other"
        },
        {
          "title": "Can IPOs Finance the AI Boom? | Google's TPU Push | Storage as a\r\n Competitive Advantage",
          "sender": "BigDATAwire Weekly Update",
          "date": "27 May 2026",
          "snippet": "To view this email in your browser, click here (https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3fwDnIsMPezvvLq%2F…",
          "link": "https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3fwDnIsMPezvvLq%2FsvzCl1x%2BRLJ33JyR%2Bf9SuZlgO%2BR2PF0HATE4tTQ%3D%3DA",
          "category": "other"
        },
        {
          "title": "🚢  The \"ship or walk the plank\" app",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "27 May 2026",
          "snippet": "---------- View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/52d21359-5053-481c-aee…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGVs4vX6nMmv7HEHSUyodkgNXoL_H8HuAmsu9BFB_fMPvU7gny9fctJHr1mPvi12euNkrgUBIx_tFZtz36Jc2lsPP0EGTpFbJziXqtFjXXRdbtU9tPi636Hmw5UepFUM03Ocmn-8G-qeWDiJPBX1N9m2og5gw8W0AhJ8sp3tjDh2mtu8xrnrVab0ff6yf87e8IklmO25uo1Y8CkwuDAERaWii7ZgfwT35QgjQc4GzFS4g2TdI-N64Lz8cHz-tlVDm_3kHuuL2yIr5tFERho7rXnmCIoe6oFkqGirmlm7B1zoFuL25OCkTSz7pOfeh24Gqt10lps3Ki6jqKTUdDx-bAUG2N1a1UJ4GboEMrdCnEuarRxaiS6XrvTv3ODymQyJ6eotF7rSwFeCxAa_4bxXFlcIR8NUnpWbAv0BVALEbmXtXZtFUWWZZlXQzp-1B7PBcDIusLEh_7N3t2Ltj4sygFh6qRs41CCuGChtzVfKiOUrzLl3hjeTmO4qPQc3FhRi_Fnhvi8iTrL9p6QdRWjVeGbPUBqRX0USggYoXXwcxcCZpBmvyM0F9v1ggQkHwhcS28E_ovZiqMHirV_GpL-nX6CNncuGYCDYqclRGCHUv9M5buD2y3E3mo9qkAWiICTWiN6e8NNC3rbStXo5xXXi4IoWoK2380IX4W75ZmU-6_qSGIbdxl0UB6TM1iO00Qeau8ennMw1D0gZiwpsohnJMSAoS4EFinhLeSpdCbpHfPdC6Srd-EK0AJo0M9bab0-WORk/4qz/jXAynZI5S4aUDVYAG4nqgQ/h0/h001.YEmE7-0acWMJMUvuuvj0AAzsYntd5vF792HcpEUqkOw",
          "category": "other"
        },
        {
          "title": "👀  The truth about agentic coding models",
          "sender": "The Code",
          "date": "27 May 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/2ae53dd8-beae-4d8c-ad1a-7e27ee761…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.kro7WBsAmEsY5mGgiUDePbOdMF_BvViPt7FxYKgxL9u030KnWr-X-SL1VvW4mqBo6USDvJLGq4yq-HGolIYHtSiv8nFwgLmOKZMZuNrgXUaiTEXRnmf2I9dgEQVEU4Cd1tusob77OPmzBxJ2q83t13iMlbNjqbC7TIxRR3AfxDmGfRp-fR7yLHTjypKlaSqGpbS_UauSwpyhSU7eWPF9I9qN_csLDIELrvdulJeJtwmwC0LETynhehs6NodGMkgOuaqQ2D2XVbILlxLmsIrDdRyjKQwgV_pwyQ5zgsUIcs5-vxmnruRCsKxkh9VU9GOhOWvA1pU8BaO4wLY1_78yKBtOe1_O8nwWwwX4rSf-ius_whjDhtEgTgudfNLx0yaiG4OFZ63RrO8hSScAfrxfjaaVVMBvYYYlawiBO8Q5i-sAH4BpeZQd3NVSWPSr0dba08Hsr_mIspQ089sK_lQp4MVzCA8Tycm3XfSmBZbFJ9-gjMnz-wgTAo7wsHwD-iCvucpEFzHlr32Ijc39KD22mgGyMDO_Jt8KfKP9ee29BlG6uXyXR8qm45-ffIQkwtZEEqMMfDzI_N_H9WfFaHJHsbvGiVtUV661F_zc6sPfJKH-k7BlxpQvIOybzWH2Rv0VF4uevdnA4sYAfTIj73Y3LZiHXOcwsvqH1FfIaZ3m2dTKA8R4lpObHmJrvnvnPw5qhQLBNVxcbFRdqQ4J-sJyC0D7tgxOES4uZObE6avtTk9X-iTUPfIj4RV60nrepcQ6ISMN4DnL2SD_BQDmp2l2k6e4PW3a9LbqFmz0PdXDenwcOj-ZBrP9ln3d98bOdh_sQWmzyx0_WXkKMViKEZ13jwPGZtQojUuP_fsfEbZBSX3J_fEhWlJ6jqKCA9pb50Vt/4qz/zNQuHm5vTv2eXwNHioDqYA/h0/h001.KS2-pHKgzp6DeY7eVLI2QvQJ6xGevfyzuRuHRotYnC8",
          "category": "other"
        },
        {
          "title": "You're in my top 5% of readers 💌",
          "sender": "Tom's Marketing Ideas",
          "date": "27 May 2026",
          "snippet": "Hey, You’ve opened 10+ of my emails this year. That puts you in the top 5% of my readers (Substack’s 5-star subscribers, further filtered by open rate). Which m…",
          "link": "https://substack.com/@marketingideas",
          "category": "other"
        },
        {
          "title": "🎙️  Exclusive: Demis Hassabis on when AGI arrives",
          "sender": "The Rundown AI",
          "date": "27 May 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/exclusive-demis-hassabis-on-agi-curing-diseases-with-ai?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=e…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_FgJCrW8Kt-qKLlbadoQICHK6jk1KimqEi_KWh72O9_Ec-jOgQgMMMye3bJpjitc7-4n3CseD9UJK_HogrIkyJcfLtLFgsN_dAH0NRsS_y5_56MOoau2W_NLeiqKh8b_RkFNYrkH1Ee-G0PAdBTZUeMTvWfWUeP1ehKunyiCgX1_Tk7wyRgkc10r0IT424B8om0Q5cBQU81z60uAbS3IYQ0ZdpYwAxvaNoFwPFRuaba1-2dFI2pDfw5JM2m1vHNA6y7PmU_cdqom_viXOrn_VhhBYMZJKRsfIknOBDlCWLg5aGv-1u9r9R_nwTegdOl25HDb0YcpMWKYtZniF_UzSjoUFivQ39kNKFW2umi6N0L6GJdC_D3fmJb7_e1QfLNtddfnmB1yslgMX_PXv7Te1sreFlMP9_F1wky_rMZIVEHgMW--gnWK7qKmn5mXBQhxoXb2IyusN2V4_69lphtSstZCvLW-qfSOKa9MYPdny81kpXuB1C_YG3-ChV7TPGkxHtQ-2clMvH0xFrtW-1Gbisg-lTxl8kfdMqZcaJpHY7ljh4YXh57ClBMpBZjMo-IMd1ym9tTQZ-HjJz2vBvWzcyo54e3yJwj_ldeEJ9saMp1MNx-L2A0sCvshvoFvpGwU957vOEmtEIr_W0vDpFd0TpixP3XAA_iomwqvSjskNjX4B4JamG0aB3Wc5fNw1nNH4uH4PYSCavTQU6_2nJs9kLQiqqb-PeEpYv3DTn2DETRve52ax_ks-NH6nf1sYJNjXOco7ezM7TorQPJylBUWw3r/4qz/gnwVF9enQJ-6QFVkCioWSA/h0/h001.UwlmAVmlJ8KlTu1a1CxIoDpjD4hFALpF4xRBNknH3xU",
          "category": "other"
        },
        {
          "title": "Insights from our first AI Club 🪄",
          "sender": "🌀 Refactoring",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://refactoring.fm/p/insights-from-our-first-ai-club Hey, Luca [ https://substack.com/redirect/8da13466-3b1f-42f9-b276-924191dc…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9yZWZhY3RvcmluZy5mbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZyZWZhY3RvcmluZy5mbSUyRnAlMkZpbnNpZ2h0cy1mcm9tLW91ci1maXJzdC1haS1jbHViIiwicCI6MTk5MTc1NzI2LCJzIjo2NDA5OSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk4NjU3MzUsImV4cCI6MjA5NTQ0MTczNSwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.1sidaaGLqqnjOBsZdY1gMUh-INmfpPFCdiEURcpFkp0?",
          "category": "other"
        },
        {
          "title": "[AINews] New AI Infra decacorns: Fireworks, Baseten (with OpenRouter on the\r\n way)",
          "sender": "AINews",
          "date": "27 May 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-new-ai-infra-decacorns-fireworks Take the 2026 AI Engineering Survey [ https://substack.com/redir…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLW5ldy1haS1pbmZyYS1kZWNhY29ybnMtZmlyZXdvcmtzIiwicCI6MTk5NDEyMTQ0LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3OTg1MzAxNCwiZXhwIjoyMDk1NDI5MDE0LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.y7WYwPuyZ7W98Ikr5PZ6vRyOPNapx_9Y_CGJ6sLSGMI?",
          "category": "other"
        },
        {
          "title": "Raging Perspective",
          "sender": "Scott Galloway",
          "date": "26 May 2026",
          "snippet": "View this post on the web at https://www.profgmedia.com/p/raging-perspective Rage is a dish best served live. Starting May 27 (that’s tomorrow), we’re debuting …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cucHJvZmdtZWRpYS5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnByb2ZnbWVkaWEuY29tJTJGcCUyRnJhZ2luZy1wZXJzcGVjdGl2ZSIsInAiOjE5OTM5MjY0OCwicyI6NzE1NzQxMSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3Nzk4Mzc3OTIsImV4cCI6MjA5NTQxMzc5MiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.JfkU1ZqW6eChqTK4NLYxnIHGDbMIUzS0d9UT9cN6jug?",
          "category": "other"
        }
      ]
    }
  ]
};
