// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-09-15 13:00 UTC",
  "date_range": "14 Sep 2026 – 15 Sep 2026",
  "total_scanned": 39,
  "total_categorised": 23,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 6,
      "top": [
        {
          "title": "[AINews] AEF-1 standard emerges for Third Party Evaluators, as Xai, OpenAI,\r\n and Anthropic all cosign",
          "sender": "AINews",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-aef-1-standard-emerges-for We last highlighted the pacing debate in July when Pacing the Frontier…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWFlZi0xLXN0YW5kYXJkLWVtZXJnZXMtZm9yIiwicCI6MjE1NzY5NDk5LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ0ODAxNSwiZXhwIjoyMTA1MDI0MDE1LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.81RL8keCMWOr6coUxrr-o45x9ziWRMZbjTUwfygr0Fg?",
          "category": "hpc_ai"
        },
        {
          "title": "LLMs as a Judge: How to Know if Your LLM is Healthy",
          "sender": "ByteByteGo",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/llms-as-a-judge-how-to-know-if-your Why you should evaluate every AI agent before shipping to product…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGbGxtcy1hcy1hLWp1ZGdlLWhvdy10by1rbm93LWlmLXlvdXIiLCJwIjoyMTUxNTExMDIsInMiOjgxNzEzMiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODk0MDA3MTgsImV4cCI6MjEwNDk3NjcxOCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.RR4bKIY0vhsdjeOD2H8rPOxx9ZcK9bYtK73xMBG8S5I?",
          "category": "hpc_ai"
        },
        {
          "title": "The Technology Powering the Next Generation of AI & HPC",
          "sender": "Technology Leaders Showcase",
          "date": "14 Sep 2026",
          "snippet": "To view this email in your browser, click here https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3rbok4ZoBxgsVW7h9UJ…",
          "link": "https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3rbok4ZoBxgsVW7h9UJvueBOZLk9mt%2FwHlH16vI9Z4ZBU3xksp0RsQw%3D%3DA",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "[AINews] AEF-1 standard emerges for Third Party Evaluators, as Xai, OpenAI,\r\n and Anthropic all cosign",
          "sender": "AINews",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-aef-1-standard-emerges-for We last highlighted the pacing debate in July when Pacing the Frontier…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWFlZi0xLXN0YW5kYXJkLWVtZXJnZXMtZm9yIiwicCI6MjE1NzY5NDk5LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ0ODAxNSwiZXhwIjoyMTA1MDI0MDE1LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.81RL8keCMWOr6coUxrr-o45x9ziWRMZbjTUwfygr0Fg?",
          "category": "hpc_ai"
        },
        {
          "title": "LLMs as a Judge: How to Know if Your LLM is Healthy",
          "sender": "ByteByteGo",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/llms-as-a-judge-how-to-know-if-your Why you should evaluate every AI agent before shipping to product…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGbGxtcy1hcy1hLWp1ZGdlLWhvdy10by1rbm93LWlmLXlvdXIiLCJwIjoyMTUxNTExMDIsInMiOjgxNzEzMiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODk0MDA3MTgsImV4cCI6MjEwNDk3NjcxOCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.RR4bKIY0vhsdjeOD2H8rPOxx9ZcK9bYtK73xMBG8S5I?",
          "category": "hpc_ai"
        },
        {
          "title": "The Technology Powering the Next Generation of AI & HPC",
          "sender": "Technology Leaders Showcase",
          "date": "14 Sep 2026",
          "snippet": "To view this email in your browser, click here https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3rbok4ZoBxgsVW7h9UJ…",
          "link": "https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3rbok4ZoBxgsVW7h9UJvueBOZLk9mt%2FwHlH16vI9Z4ZBU3xksp0RsQw%3D%3DA",
          "category": "hpc_ai"
        },
        {
          "title": "Vote Now! The 2026 HPCwire Readers’ Choice Awards Ballot is Now Open",
          "sender": "HPCwire Subscriber Services",
          "date": "14 Sep 2026",
          "snippet": "To view this email in your browser, click here https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3QHinEqdUyPOt9YAHns…",
          "link": "https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3QHinEqdUyPOt9YAHnsgjdoPWAheXDhGPjokxVV6UEJmWQWSCA0s4AA%3D%3DA",
          "category": "hpc_ai"
        },
        {
          "title": "⚡️  Anthropic CEO calls for AI slowdown",
          "sender": "The Code",
          "date": "14 Sep 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/fac1c159-4cb1-4241-ac36-4ee2e3dd3…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.kro7WBsAmEsY5mGgiUDePbOdMF_BvViPt7FxYKgxL9uBsQgs_AZJP-J4YAThb8auGszGZ-xeMeqRlcJnd7beSNdymoMiqanFp4qQCQnJAduhreRMH_SD_B0luXWMhxcPqbu6RB4HfeM2B14kMa4CGudKEvcteSVjaWbNNoIXE2p11vIhXEGwUsjEGXmSYFXaZu-A_sLqtI3jO2tGiOGOyllvue9Tr1xJk-seQwskO7y4HY7KYthc9blg71YXmcAxo7q1GqW7pXaa_MGWN846K_P-Cmh0ciFEB1U_4DxbjrCTxwKtMlQu-2qgWVYGqrhngs730trV4yjSH4-ookvNlCOWi9uwwXzsXX7hgXbKpNDiar35HlXx3NNSv057bEsvT1uHiC7vRQqZoZcgzsEsQgeiGBGd1fa9mb5ezXbzGBY9Sn-azdWj2pVZdEwOBvaYuHjQoupOxClO_jzQ2q_T7LuXb3BMkba8cJPHLpam7BKU3wn0QCeVOnCOyPhJ34HKkiNdTOxz_YnTsbVqvv_DX_edMnz6xrvqA4cWAD_1ct-CNfbqVr2CTFMNdi6q-tDzKBjRLIFuFITcoxS2B2Aoyp7YGUbPOBzswnRhy-fxgfN_RpELGfcj0JiUmYX_SGo5RjhnwokVmazP33m6o_ZYX2Yf8Fbdfs1tFDjlffktSbxl8fQwLp2BEuOn3IDda5vaqBTdb9HeVKXQ66OpYbJJxQ7n5aaNvKp7fzqEAUiN-3jNXzaBQfqZpxcrxFyT33uJCf42qO_9ic-U9ki9doX4dQ/4u1/7el245ZPTj6FW-8MUWkSrA/h0/h001.xNyuebO8Z-G5CZ5cq054muER1QBjv1SbveCcg8tnaAY",
          "category": "hpc_ai"
        },
        {
          "title": "HPC AI // Sync Issue 35",
          "sender": "HPCwire Sync",
          "date": "14 Sep 2026",
          "snippet": "#outlook a { padding: 0; } .body{ font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Geneva, Verdana, sans-serif; width: 100% !important; -webk…",
          "link": "https://tabor.dragonforms.com/tabor_pref&amp;r=5801D9452678H4Z",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "product",
      "name": "Product Management",
      "emoji": "🗺️",
      "count": 2,
      "top": [
        {
          "title": "60+ new creative growth ideas",
          "sender": "Lenny's Newsletter",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/60-creative-growth-ideas 👋 Hey there, I’m Lenny. Each week, I share deeply researched product, g…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRjYwLWNyZWF0aXZlLWdyb3d0aC1pZGVhcyIsInAiOjIxNDM2MDM2NiwicyI6MTA4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5NDc3MDU2LCJleHAiOjIxMDUwNTMwNTYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.UBvVyUrGQzYyNHbJmQT_-ZaZuUArpZGPKSZuHLCLQyA?",
          "category": "product"
        },
        {
          "title": "🎙️ How I AI: How two SpaceXAI designers use Grok Bot to do their jobs",
          "sender": "Lenny's Newsletter",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/how-i-ai-how-two-spacexai-designers How Grok Bot designers use AI agents to build personal sites…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRmhvdy1pLWFpLWhvdy10d28tc3BhY2V4YWktZGVzaWduZXJzIiwicCI6MjE1MTAyNTAzLCJzIjoxMDg0NSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODkzOTkxMjIsImV4cCI6MjEwNDk3NTEyMiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.32BNq5alK-na-a968TlzVOV9Ip5G158_o7nWJW6eneI?",
          "category": "product"
        }
      ],
      "all": [
        {
          "title": "60+ new creative growth ideas",
          "sender": "Lenny's Newsletter",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/60-creative-growth-ideas 👋 Hey there, I’m Lenny. Each week, I share deeply researched product, g…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRjYwLWNyZWF0aXZlLWdyb3d0aC1pZGVhcyIsInAiOjIxNDM2MDM2NiwicyI6MTA4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5NDc3MDU2LCJleHAiOjIxMDUwNTMwNTYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.UBvVyUrGQzYyNHbJmQT_-ZaZuUArpZGPKSZuHLCLQyA?",
          "category": "product"
        },
        {
          "title": "🎙️ How I AI: How two SpaceXAI designers use Grok Bot to do their jobs",
          "sender": "Lenny's Newsletter",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/how-i-ai-how-two-spacexai-designers How Grok Bot designers use AI agents to build personal sites…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRmhvdy1pLWFpLWhvdy10d28tc3BhY2V4YWktZGVzaWduZXJzIiwicCI6MjE1MTAyNTAzLCJzIjoxMDg0NSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODkzOTkxMjIsImV4cCI6MjEwNDk3NTEyMiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.32BNq5alK-na-a968TlzVOV9Ip5G158_o7nWJW6eneI?",
          "category": "product"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 14,
      "top": [
        {
          "title": "Apple’s  OS 27 Lands  🍎, Google Eases M365 Exits  🔄,  AI Agents Get Employee Rules  🤖",
          "sender": "TLDR IT",
          "date": "15 Sep 2026",
          "snippet": "Apple has released its annual software wave across iOS 27, iPadOS 27, macOS 27, watchOS 27, visionOS 27, and tvOS 27. For IT teams, this officially ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Controllers  🎮,  Slack Vibe 💬,  Miro Acquisition  🤝",
          "sender": "TLDR Design",
          "date": "15 Sep 2026",
          "snippet": "Apple is reportedly developing its own game controllers for iPhone, with beta code revealing two models that include thumbsticks, a D-pad ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI agents do business  🤖,  dashboards in chat  📊,  writing good design docs 📝",
          "sender": "TLDR Dev",
          "date": "15 Sep 2026",
          "snippet": "Successful research strategies often survive an extreme information bottleneck, suggesting that they capture real structure instead of ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "Apple’s  OS 27 Lands  🍎, Google Eases M365 Exits  🔄,  AI Agents Get Employee Rules  🤖",
          "sender": "TLDR IT",
          "date": "15 Sep 2026",
          "snippet": "Apple has released its annual software wave across iOS 27, iPadOS 27, macOS 27, watchOS 27, visionOS 27, and tvOS 27. For IT teams, this officially ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Controllers  🎮,  Slack Vibe 💬,  Miro Acquisition  🤝",
          "sender": "TLDR Design",
          "date": "15 Sep 2026",
          "snippet": "Apple is reportedly developing its own game controllers for iPhone, with beta code revealing two models that include thumbsticks, a D-pad ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI agents do business  🤖,  dashboards in chat  📊,  writing good design docs 📝",
          "sender": "TLDR Dev",
          "date": "15 Sep 2026",
          "snippet": "Successful research strategies often survive an extreme information bottleneck, suggesting that they capture real structure instead of ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Siri AI  📱,  Zuckerberg profile 🧍‍♂️,  Xcode 27 👨‍💻",
          "sender": "TLDR",
          "date": "15 Sep 2026",
          "snippet": "iOS 27 marks the beginning of an iPhone divide: only Apple Intelligence-capable models will get Siri AI and other AI-powered features. The new Siri ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Product judgment still wins  ⚖️, cracks in the AI thesis  🪨,  PLG sales problems 🤔",
          "sender": "TLDR Product",
          "date": "15 Sep 2026",
          "snippet": "Don’t automate away productive friction. Use AI for routine work, but keep humans in the conversations where judgment and alignment happen. ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Amodei slows frontier  🛑,  ARC-AGI-4 🧠,  Cursor Projects 👨‍💻",
          "sender": "TLDR AI",
          "date": "14 Sep 2026",
          "snippet": "Anthropic CEO Dario Amodei called for slowing the rate of frontier AI capability development and proposed measures including independent evaluators ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Tesla re-releasing Roadster  🚗,  Apple's Neural Engine decomposed  🧠,  SpaceXAI's massive battery  🔋",
          "sender": "TLDR Hardware",
          "date": "14 Sep 2026",
          "snippet": "Tesla posted \"Go for launch\" with a \"10.01\" graphic, pointing to an October 1 reveal of the second-generation Roadster, first announced back in 2017 ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "GitLab CVSS 10 flaw  🚨,  Revolut data breach 💳,  Fake GTA 6 malware  🎮",
          "sender": "TLDR InfoSec",
          "date": "14 Sep 2026",
          "snippet": "GitLab has patched CVE-2026-85706, a CVSS 10 path traversal bug in the repository commits API that let unauthenticated attackers read arbitrary files ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI gets a control plane  🧠,  Windows loses its voice  🔇,  Agents get an API 🤖",
          "sender": "TLDR IT",
          "date": "14 Sep 2026",
          "snippet": "Salesforce has introduced the Enterprise AI Harness, a composable architecture featuring six trusted capabilities and an AI Control Plane ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "WhatsApp iPad Sidebar  💬,  Premiere AI 🎬,  Firefox Redesign  🦊",
          "sender": "TLDR Design",
          "date": "14 Sep 2026",
          "snippet": "WhatsApp is expanding its Liquid Glass redesign for iPad with a new Mac-style sidebar that replaces the bottom tab bar, offering quicker access to ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Smart model routing  🛣,  using OpenRouter correctly  🔢,  measuring code sloppiness 🧹",
          "sender": "TLDR Dev",
          "date": "14 Sep 2026",
          "snippet": "Smart routing sends routine requests to cheaper models and reserves stronger ones for difficult or high-risk work. In one example workload ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Spacelift Flows  🌊,  Evals in CI/CD 📜,  RubyGems Cyberattack  🥷",
          "sender": "TLDR DevOps",
          "date": "14 Sep 2026",
          "snippet": "Spacelift Flows brings Day 2 infrastructure operations into a visual, auditable workflow platform, enabling teams to automate incident response ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI slowdown  🛑,  Tesla Roadster v2 🚗,  forward deployed engineers 👨‍💻",
          "sender": "TLDR",
          "date": "14 Sep 2026",
          "snippet": "Anthropic's CEO recently released a 3,800-word essay calling for a global slowdown of AI development. He said that while the technology offers ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Postgres at 118M QPS  🏎️,  ChatGPT Work Data Agent  🗣️, Lyft’s  Travel-Time Map  🚕",
          "sender": "TLDR Data",
          "date": "14 Sep 2026",
          "snippet": "Coding agents now produce competent PostgreSQL schemas, but they tend to stack indexes onto hot operational tables. In a measured support ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "stoic",
      "name": "Stoicism & Philosophy",
      "emoji": "🧘",
      "count": 1,
      "top": [
        {
          "title": "Write It Down Before You Forget Who You Were",
          "sender": "StoicWisdoms",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/write-it-down-before-you-forget-who A quick note before we begin: My ebook STOIC CONFIDENCE has been…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZ3cml0ZS1pdC1kb3duLWJlZm9yZS15b3UtZm9yZ2V0LXdobyIsInAiOjIxNTY0MDAxNiwicyI6MTgwMTMzMywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODk0NzAxODAsImV4cCI6MjEwNTA0NjE4MCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.53fCrFVUfvGrH1CWDCljVB8Sqkuu0vNUYdxlPcTAlMY?",
          "category": "stoic"
        }
      ],
      "all": [
        {
          "title": "Write It Down Before You Forget Who You Were",
          "sender": "StoicWisdoms",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/write-it-down-before-you-forget-who A quick note before we begin: My ebook STOIC CONFIDENCE has been…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZ3cml0ZS1pdC1kb3duLWJlZm9yZS15b3UtZm9yZ2V0LXdobyIsInAiOjIxNTY0MDAxNiwicyI6MTgwMTMzMywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODk0NzAxODAsImV4cCI6MjEwNTA0NjE4MCwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.53fCrFVUfvGrH1CWDCljVB8Sqkuu0vNUYdxlPcTAlMY?",
          "category": "stoic"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 16,
      "top": [
        {
          "title": "The Education Crisis",
          "sender": "Ed Elson",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://edwardelson.substack.com/p/the-education-crisis Last week, as the world bickered about whether or not AI will “kill all hum…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9lZHdhcmRlbHNvbi5zdWJzdGFjay5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGZWR3YXJkZWxzb24uc3Vic3RhY2suY29tJTJGcCUyRnRoZS1lZHVjYXRpb24tY3Jpc2lzIiwicCI6MjE1NzQ3MDU2LCJzIjo0ODU2NTg2LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ3MDg1MywiZXhwIjoyMTA1MDQ2ODUzLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.uqvlLsExxDLPzcm6tUYFLDxBidsFP5ov10Zp7AiPgDw?",
          "category": "other"
        },
        {
          "title": "✋  Trump hits back at AI labs",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "15 Sep 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/8397f8bf-477f-42ba-94b0-b71564b1e…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGVz9owOcNzJST2LW_PAwk-cTga7vmG35Rl6Ysndpjm4y_YDar66vaUm7rEhoJb0XZ_qFakZcOBdEhm_C9alm3ukOp7P5JOl4irCvxVDF4nsVgax9I9QUbQcX0DzKElX0mYokbOdZZ_a-obRCavlQTnxgTsGxXWaY9qw2jhHdpRzyPk8Nzvo2Prawdulri_rFlGy5w2FolNQZWu52Nyhc-gziWwJbPgCoKELsrZGsRJnXy5SsSKttq0wy6HNB8JqAqcygUyg_JydaP0PZczmMqad4N6c8IrKu4cKpCU_6oQTsLuJgTsX8FAVnlepZLyHKI8PYHuCFCyf9HpBhPwcDgOu_IYofc7SBhua90KJzniv0zgVF9rN-rWL8TyhlNbi-GQiz3KFQrjdofo0YXosk7Ln46f3ysr2WGG9ZlSc9X91GKbWONpu5tuhaotNsS8DDD17-cAeogSrZFok_bgNwI0vZc4TFLFnZAXu26jtTDhU0vco7Ogws1Wo90l7JY779BsQm0_yErzYsvu8rX3HTWq-v5wPpfwqpaBMKwXw8rEQ_LU7u6UehhM92bcw8xnJLVoBlEC0G6ux4lVkToQmetXxBfiogONPdXLfNY2JlipYqbj9QUDtkPFiwnUmL21_9i4V24os52KiszuK8n-eDW7aW-cp4AsqVs8ZgiVqu2lB43nEeA1AZO_XKuzouvfyZeo/4u2/19TaX_kQS_adqwM9AJtwbw/h0/h001.RGBHOGz-foA7G_Csd2bdyIynrVLxKdRTi4xG-uSf1HA",
          "category": "other"
        },
        {
          "title": "1,503 US Early-Stage Investors, Mapped: Pre-Seed to Series A",
          "sender": "The VC Corner",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/us-early-stage-investors-database-map-2026 Founders talk about the Series A crunch as a feeling. It’s…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGdXMtZWFybHktc3RhZ2UtaW52ZXN0b3JzLWRhdGFiYXNlLW1hcC0yMDI2IiwicCI6MjE1ODAyMTI5LCJzIjoyMTI1MTgzLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ2ODc5NywiZXhwIjoyMTA1MDQ0Nzk3LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.9cLgPQcTijuWevkPx8EWWz0NV7faQOKNFxfuKLQi0cM?",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "The Education Crisis",
          "sender": "Ed Elson",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://edwardelson.substack.com/p/the-education-crisis Last week, as the world bickered about whether or not AI will “kill all hum…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9lZHdhcmRlbHNvbi5zdWJzdGFjay5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGZWR3YXJkZWxzb24uc3Vic3RhY2suY29tJTJGcCUyRnRoZS1lZHVjYXRpb24tY3Jpc2lzIiwicCI6MjE1NzQ3MDU2LCJzIjo0ODU2NTg2LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ3MDg1MywiZXhwIjoyMTA1MDQ2ODUzLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.uqvlLsExxDLPzcm6tUYFLDxBidsFP5ov10Zp7AiPgDw?",
          "category": "other"
        },
        {
          "title": "✋  Trump hits back at AI labs",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "15 Sep 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/8397f8bf-477f-42ba-94b0-b71564b1e…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGVz9owOcNzJST2LW_PAwk-cTga7vmG35Rl6Ysndpjm4y_YDar66vaUm7rEhoJb0XZ_qFakZcOBdEhm_C9alm3ukOp7P5JOl4irCvxVDF4nsVgax9I9QUbQcX0DzKElX0mYokbOdZZ_a-obRCavlQTnxgTsGxXWaY9qw2jhHdpRzyPk8Nzvo2Prawdulri_rFlGy5w2FolNQZWu52Nyhc-gziWwJbPgCoKELsrZGsRJnXy5SsSKttq0wy6HNB8JqAqcygUyg_JydaP0PZczmMqad4N6c8IrKu4cKpCU_6oQTsLuJgTsX8FAVnlepZLyHKI8PYHuCFCyf9HpBhPwcDgOu_IYofc7SBhua90KJzniv0zgVF9rN-rWL8TyhlNbi-GQiz3KFQrjdofo0YXosk7Ln46f3ysr2WGG9ZlSc9X91GKbWONpu5tuhaotNsS8DDD17-cAeogSrZFok_bgNwI0vZc4TFLFnZAXu26jtTDhU0vco7Ogws1Wo90l7JY779BsQm0_yErzYsvu8rX3HTWq-v5wPpfwqpaBMKwXw8rEQ_LU7u6UehhM92bcw8xnJLVoBlEC0G6ux4lVkToQmetXxBfiogONPdXLfNY2JlipYqbj9QUDtkPFiwnUmL21_9i4V24os52KiszuK8n-eDW7aW-cp4AsqVs8ZgiVqu2lB43nEeA1AZO_XKuzouvfyZeo/4u2/19TaX_kQS_adqwM9AJtwbw/h0/h001.RGBHOGz-foA7G_Csd2bdyIynrVLxKdRTi4xG-uSf1HA",
          "category": "other"
        },
        {
          "title": "1,503 US Early-Stage Investors, Mapped: Pre-Seed to Series A",
          "sender": "The VC Corner",
          "date": "15 Sep 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/us-early-stage-investors-database-map-2026 Founders talk about the Series A crunch as a feeling. It’s…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGdXMtZWFybHktc3RhZ2UtaW52ZXN0b3JzLWRhdGFiYXNlLW1hcC0yMDI2IiwicCI6MjE1ODAyMTI5LCJzIjoyMTI1MTgzLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQ2ODc5NywiZXhwIjoyMTA1MDQ0Nzk3LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.9cLgPQcTijuWevkPx8EWWz0NV7faQOKNFxfuKLQi0cM?",
          "category": "other"
        },
        {
          "title": "👎  Trump, China both shoot down the AI slowdown",
          "sender": "The Rundown AI",
          "date": "15 Sep 2026",
          "snippet": "^**[Read Online](https://therundownai.beehiiv.com/p/trump-china-both-shoot-down-the-ai-slowdown?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eX…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.KT4rQsO6sHS_v2VASG2xupywTByilB7vBf1gbeXMnd8DefSH3PukMktwD_yZvVdjkO0HEDaToIoATqC9lyr_m1T_wNArCKtCsNIAy9U4U4m787OiXweTinczNkjXxJHOsDul6lMAFTdDKeGyO8rB3aDDbXasgAkzYovjdvmSsg8wK2iCa9PzBNRb7jWHb7L-kCeRXgPC5MCmbNCU--0lRoSXBPOqM0nwN7mZym50CEnR6Flg0yB6L4lHsNHzBD6ebYHM0tWh0tpLx86clKdm0oSasF6srQ2rbPT70JP2y-SI6DCvtnisMKTLGqnzpoUIFHY5vKBYnPdyJmLO31V7f-No2xt74r2GTxcHQnxSwyTugCMpv7gbipUdJ5ry9Wbk84MnFS1lcJWJKSeJeAEKFcIsvw3oJpu3Eg06c0ETRfVq9ABHDZTOzQkbTm_LE9mPdKMDXY-KgpsWrCCWqhQcg4iMd9P0Xx-HIdMut4kb2OAIKNXObkm6P6CrY0TiF_Qob5tP-SG_bciQdyZFqwfkly_wVJlgHhrPXLw9mMaO_y4poV4Wtv5Atr2VSF8CCa91MA8CcHckA4sOAIWlGNUGyLyw_eTrTuqVyNn2q_VIMiQQT4NGR3pj87rT1FEOVV5Ym9kXE-aBcazB3ySdBEJz1hc61sIC8f-9nQ-i8NVem3RHPaq-bumvBt992OAioJtzaTcagBZOLJ42nMShqYZNEd1iXsgWUvcST8Nn3JenUCwDuoRu7WAY69FbrePs4dIkNAmEIcOB8FpQJd6A0y88uQ/4u2/Q7dFePP8RdyI13PiA6hIWA/h0/h001.5vrqqNDzWj05IcozXTmZA_wlb5XF58Sw7Yp18qtrPLk",
          "category": "other"
        },
        {
          "title": "The simplest way to track your success this  BFCM…",
          "sender": "Nord Media",
          "date": "14 Sep 2026",
          "snippet": "************************************************* The simplest way to track your success this BFCM… ************************************************* You don’t …",
          "link": "https://735d96f7.click.convertkit-mail4.com/mvupl3xg6pt5hqxnn8vfmhred4eoluq7nd6vxelvexmr8gpn6pm9kgm75odvogm7l3wq3nwgnzl2mklgrnoz0r573k2wmk75powomgnmv5wn9nenk2rok5mgnv5h9vnzz/48hvh7umx32xozcqu7/aHR0cHM6Ly93d3cubXlzYXRoaS5pby9kZW1vP3V0bV9zb3VyY2U9a29keSZ1dG1fbWVkaXVtPXBhcnRuZXImdXRtX2NhbXBhaWduPW5vcmRfbWVkaWE=",
          "category": "other"
        },
        {
          "title": "Does TV actually suck now?",
          "sender": "The Substack Post",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://post.substack.com/p/does-tv-actually-suck-now-emmys To kick off awards season, The Substack Post asked Emily Kirkpatrick , …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9wb3N0LnN1YnN0YWNrLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZwb3N0LnN1YnN0YWNrLmNvbSUyRnAlMkZkb2VzLXR2LWFjdHVhbGx5LXN1Y2stbm93LWVtbXlzIiwicCI6MjE1Njg1NzA2LCJzIjo3MzcyMzcsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5NDE0MTk4LCJleHAiOjIxMDQ5OTAxOTgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.ioMtTFxwygInR1B1L1JfnRjI0TP_GrBvy-adISrNM6s?",
          "category": "other"
        },
        {
          "title": "Why you should work on AI for AI Research — Richard Socher of Recursive",
          "sender": "Latent.Space",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/recursive From helping pioneer core ideas in NLP to now building AI systems that can automate AI researc…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGcmVjdXJzaXZlIiwicCI6MjE1Mjg5ODExLCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTQwMjMwNCwiZXhwIjoyMTA0OTc4MzA0LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.yuQxmonE7nDH_X6CS3BThONp-_e45wPtQS0R0uZjWSA?",
          "category": "other"
        },
        {
          "title": "The AI CEOs Asked for a Brake. Trump Said No. Here Is How to Plan Anyway.",
          "sender": "The VC Corner",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/ai-doom-decision-framework-four-scenarios-2026 Three people with every commercial reason to accelerat…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGYWktZG9vbS1kZWNpc2lvbi1mcmFtZXdvcmstZm91ci1zY2VuYXJpb3MtMjAyNiIsInAiOjIxNTY3NDcyMCwicyI6MjEyNTE4MywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODkzOTk0NjUsImV4cCI6MjEwNDk3NTQ2NSwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.ti3VPxmCmtQbMLmNXLg_BMaZOs5bZCsh4Uz3MKwZzHc?",
          "category": "other"
        },
        {
          "title": "🤖 Japan’s  latest answer to home robots",
          "sender": "The Rundown Robotics",
          "date": "14 Sep 2026",
          "snippet": "^**[Read Online](https://robotnews.therundown.ai/p/japan-latest-answer-to-home-robots?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJzY3JpYmVyX2lkIjoiZTM…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.GQOM8q4ys-vZgCzT2HGlhRR7J-xBT4QBkF5vOL2NbkBIrSN-GLi8SjGkgbDOSGTWhWoIQt_P7t7WFkiB9e9GQCHMaV2zPq62wNirh9PZl9SHXJ-OaW9H9ATPgKLIXVP8jW5aQX9aIzKBeVD8Uh2faXofJEzJKD1U3efKesILVMI4mXAuVXZ5sxw0lapbjD9ry1siqfRCFMFclV_zloMbLDqNS_uBz1MwXN7orRTYRUxS_G1M_-1b_mGlCXLf5XF6HezFRwDK3HI1V9z-0xmawUdOgiEBqNzDF0YD3VKkJ4cs7RAux5jwdvS7frOTEOy6OyiaCRyLIusNB0cDdHqNyaeBGPsj2bi4WOZCzCpHrQzm_HgmpAobHg20_fF291hgdjAmCl_HTngQ_nThGEA8ElRKIURyxqIfRNIR9h8Qi9OWZCqK3Pn291kGd9XuzDc6lOYRltTfaUXjcbDPvHQQxnLeV7Mw4B02zrHmPiVEEidgpPJl_3eO-wuHlkj01vhPR8PMZJyIk60QLDAYpLqGYEYyxqMTKtf8A4B4c1FToZrMzF50BtV0JbciZRqSWhrcxOtUhaCRKNGbHFdBcLB-h77JDNrlfeufzhUupJqT64vL_jAaMQ-42XYTz0yi5JvpVKwoM0WWIk-AswaTygmXpJXen2kRQulFeWxY1FQnjr7wCuNVLfHzus7mtQtjyJ8qzM1x1ei1ZzXNgLiLaScX0p9oTNWOoaoKzM_c0AXQzbY/4u1/UGs3MFhJSAKu3Go8uYKr_g/h0/h001.adAtLzQ71b70EZ5gQMCfkj2K5PEjSqpQiL-M0KPGBfE",
          "category": "other"
        },
        {
          "title": "Zuckerberg Just Killed the Prompt. Muse Takes Goals Instead.",
          "sender": "The AI Corner",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.the-ai-corner.com/p/meta-muse-ai-agent-zuckerberg Mark Zuckerberg just told you what Meta’s actual product is now. Not …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhlLWFpLWNvcm5lci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnRoZS1haS1jb3JuZXIuY29tJTJGcCUyRm1ldGEtbXVzZS1haS1hZ2VudC16dWNrZXJiZXJnIiwicCI6MjE1MzM1MjI0LCJzIjo2ODUwNTQ0LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTM5NTg3MiwiZXhwIjoyMTA0OTcxODcyLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.ZfxwKC60TjT5tqcR9n0lR7b_LydO9sabEdH0XWXbrS0?",
          "category": "other"
        },
        {
          "title": "⚔️  Amodei's (controversial) call to arms",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "14 Sep 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/04465aea-479c-449a-9cf0-25738aa56…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGUuxOF8hphbWsMuu_vfWJI7ncIyptTi6My0Mqfe58UiqGBOdIbQD2bIonaBrBUQ7nqgTaCXN6dluytRH16bdQh-JdJjOvgdyw9LZl4GgHHAmFFq9NRqU3mx0xW7Vy_IeTXp1orm9wP0bhKvlS1lIsW4q9T6CeyYJmhaM5XonI1uxAizQljSXOy4oSmz0gFP7AYAsd95_qwEFzWqk11P9YS6pdZsRd1xWzunZmmyl1tZ2DfwXLfahOrUGR98ZCHWbrTWd9yJG6UzfF2wQRrxb-W7UeqMfTAifzF2vZswQEWh10rKtfHcPooGagSQBOPZHU2JC3M94wl07s1SKQyxqHrujJXoo2tTMo3XXRATkhTCWHliB_uC9F3GL3hHvntnpkzrYBRbFWCOzPm-OSgr18kKyQZOJKEjWUEM5eLwcqDcANK5A0thXblS17xcIaXEVVADtsAqT_7sm3hzB7zyscc-9nY33L0sYcj8YqzUADjwv3hQnwfYhiKgDNdI7L_AJ3QddZ3X3fGN771nZZqxyZI5L74dSbSMwtxX5avqALFOQbYlr3UCvN1upDtXRf7ClKNE3rjErSqUS5Ecv3q68_ya7N1x6oBzNF70k-yizTXUCLIbQH2Qm8QuyQLvkQVN-JUuSYBaWCVNUWd4H1GDyI4nWwNAbA-OnpOwZSzjO6LPDjAe6mce2iRfr1KxGKW41EOMzCZlcwUSOj49SqLAkBVS/4u1/pu9AEjitT0eiqEChihHh-A/h0/h001.WdaQ8Fh227Et32GfpAXf2HQduzbv61i7I0pE5XXtveM",
          "category": "other"
        },
        {
          "title": "You’re Probably Using Claude Code Wrong",
          "sender": "Neo Kim",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/claude-code-mcp-vs-cli Get my system design playbook for FREE on newsletter signup: Share thi…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRmNsYXVkZS1jb2RlLW1jcC12cy1jbGkiLCJwIjoyMTU0MTE0MTAsInMiOjE1MTE4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5Mzg1OTg4LCJleHAiOjIxMDQ5NjE5ODgsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.XHdkbQ2OJun1EdjAr_8a6aKtpzc0aW8fmO0qGSIFIhk?",
          "category": "other"
        },
        {
          "title": "AI Safety Fears Escalate After a Researcher Quits, Warning AI Could Kill Us\r\n All",
          "sender": "Scott Galloway & Ed Elson",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.profgmedia.com/p/ai-safety-fears-escalate-after-a 70,000 That’s how many pints of Guinness were stolen from a depot nea…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cucHJvZmdtZWRpYS5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnByb2ZnbWVkaWEuY29tJTJGcCUyRmFpLXNhZmV0eS1mZWFycy1lc2NhbGF0ZS1hZnRlci1hIiwicCI6MjE1NTU1MTI0LCJzIjo3MTU3NDExLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4OTM4NDgyNSwiZXhwIjoyMTA0OTYwODI1LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.1uUtjDcKNcq6OSB5oEtHALFnZU0tbXEVCWIpHglh2f0?",
          "category": "other"
        },
        {
          "title": "😳  The people building AI want to slow down",
          "sender": "The Rundown AI",
          "date": "14 Sep 2026",
          "snippet": "^**[Read Online](https://therundownai.beehiiv.com/p/top-ai-labs-want-to-pump-the-brakes?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.KT4rQsO6sHS_v2VASG2xupywTByilB7vBf1gbeXMnd_i-ijklBfdaWQcVJWnoUeBOibxReRRG7PqgvIgF2BQUZfQJF4CT2L45jdbtjVAkJmGVJ39UfLk2rEqTW8SPxXXYRfRtnxBJZ_vh4y5srJ29fXatgp6vpJBvvQ7FeriXpLaeZlcrkT0tyBiNp2udFwX8r2nkUjQvtJzr_TSKIc798-tqhkut0CH6QqJSu1OHw24AEuAOKAjTwRF22uOm4OOfJHYT_KOZfE1aAGVdNfywO1eX9noQgrn6mRD3QwSwCwZY86Oc6QuKez9SMVfkzlkU92YUbP5ni5M1iGfv7EywdvBJRMnem_kNnv3Ns9O4gu0o7ZxulBc0dVXazDRFpduZCYT4G46V0vS_-BMi-CK9qY_F6tnhS-e7p6dHJghs2jHavqbvzjwamwIAf7sZkO_ScPCh3TyGEhgyHEPcVnNzxljy_Wt8HQ7dpDYrNXpUmuvY17tDy3URixrLITp8DGyhKTWwiv9AtPOFPOK-xBLWndD37LxygyoyuUKqvHKhJ4HRV7wZQ7_DzB_JTbFgIZHiM4B-3G9zF1B-M_ezY7onvZ5JXt9ybZBslmty1h4O5MpXSZxUpKbNMb_8zxsvnnhGtBiq4Wv0hgPBBAY9Y-18E2DSMBwu2_PET-TrOM8OqvtgrV-hIcYJpHTyrdMXrH8K6QGruzFPciHiVyWP_gbVppRpkyKU74ivBoo_s4TDeg-v5SfgJIOOGr9MvpBzx9H/4u1/dMzvXK4MTne_m01vmSQ-PQ/h0/h001.4HfxK5lquclYWmmXV02ckOiuMCDZnD3KoCrSn2S5SMo",
          "category": "other"
        },
        {
          "title": "How to Deal With Company Politics as an Engineering Leader",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/how-to-deal-with-company-politics This newsletter is sponsored by Unblocked [ https://subst…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZob3ctdG8tZGVhbC13aXRoLWNvbXBhbnktcG9saXRpY3MiLCJwIjoyMTU1NDE2NDMsInMiOjExMTU4MTUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5Mzc3NDc2LCJleHAiOjIxMDQ5NTM0NzYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.oSsxf7sFGUW1qKvVNnexTi-IBkGc97w7FKuWpM48Kv0?",
          "category": "other"
        },
        {
          "title": "\"Proof of humanity\" is the biggest marketing opportunity right now 🌈",
          "sender": "Tom's Marketing Ideas",
          "date": "14 Sep 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/proof-of-humanity-is-the-biggest Today’s ✨ free marketing idea ✨ is sponsored by enso Growth hacki…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGcHJvb2Ytb2YtaHVtYW5pdHktaXMtdGhlLWJpZ2dlc3QiLCJwIjoyMTQ5MDczMzcsInMiOjE4MTU0NzIsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg5MzY5Nzk3LCJleHAiOjIxMDQ5NDU3OTcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9._sjJaWRD3QMrQYY4Y_ymSmpwxIKobSB1LvIvGqwXpPI?",
          "category": "other"
        }
      ]
    }
  ]
};
